apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.metadata.name }}
  labels:
    {{ .Values.metadata.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{ .Values.metadata.name }}
  template:
    metadata:
      labels:
        {{ .Values.metadata.name }}
    spec:
      containers:
        - name: {{ .Values.metadata.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: POSTGRES_USER
              value: "{{ .Values.postgres.user }}"
            - name: POSTGRES_PASSWORD
              value: "{{ .Values.postgres.password }}"
            - name: POSTGRES_DB
              value: "{{ .Values.postgres.database }}"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: {{ .Values.volume.name }}
              mountPath: /var/lib/postgresql/data
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.metadata.name }}
  labels:
    {{ .Values.metadata.name }}
spec:
  selector:
    {{ .Values.metadata.name }}
  ports:
    - port: 5432
      targetPort: 5432
