apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-cast-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-cast-service
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-cast-service
    spec:
      containers:
      - name: cast-service
        image: {{ .Values.castService.image.repository }}:{{ .Values.castService.image.tag }}
        command: ["uvicorn", "app.main:app", "--reload", "--host", "{{ .Values.castService.host }}", "--port", "{{ .Values.castService.port }}"]
        env:
        - name: DATABASE_URI
          value: {{ .Values.castService.database.uri }}
        ports:
        - containerPort: {{ .Values.castService.port }}
        volumeMounts:
        - name: cast-service-volume
          mountPath: /app/

apiVersion: v1
kind: PersistentVolume
metadata:
  name: cast-service-volume-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "./cast-service/"
  claimRef:
    name: cast-service-volume

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cast-service-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi