apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cast-service.fullname" . }}
  labels:
    {{- include "cast-service.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "cast-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cast-service.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: cast-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URI
              value: "{{ .Values.postgres.database_uri }}"
          # Ajoutez des volumes, des volumes montés, des variables d'environnement supplémentaires au besoin
