apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.metadata.name }}
  labels:
    {{ .Values.metadata.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{ .Values.metadata.name }}
  template:
    metadata:
      labels:
        {{ .Values.metadata.name }}
    spec:
      containers:
        - name: {{ .Values.metadata.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URI
              value: "{{ .Values.postgres.database_uri }}"
