apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-cast-service-service
spec:
  selector:
    app: {{ .Release.Name }}-cast-service
  ports:
  - protocol: TCP
    port: {{ .Values.castService.port }}
    targetPort: {{ .Values.castService.port }}
