apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "movie-service.fullname" . }}
  labels:
    {{- include "movie-service.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "movie-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "movie-service.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: movie-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URI
              value: "{{ .Values.postgres.database_uri }}"
            - name: CAST_SERVICE_HOST_URL
              value: "{{ .Values.castService.hostUrl }}"
