apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-movie-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-movie-service
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-movie-service
    spec:
      containers:
      - name: movie-service
        image: {{ .Values.movieService.image.repository }}:{{ .Values.movieService.image.tag }}
        command: ["uvicorn", "app.main:app", "--reload", "--host", "{{ .Values.movieService.host }}", "--port", "{{ .Values.movieService.port }}"]
        env:
        - name: DATABASE_URI
          value: {{ .Values.movieService.database.uri }}
        - name: CAST_SERVICE_HOST_URL
          value: {{ .Values.movieService.castService.hostURL }}
        ports:
        - containerPort: {{ .Values.movieService.port }}
        volumeMounts:
        - name: movie-service-volume
          mountPath: /app/
