apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-movie-service-service
spec:
  selector:
    app: {{ .Release.Name }}-movie-service
  ports:
  - protocol: TCP
    port: {{ .Values.movieService.port }}
    targetPort: {{ .Values.movieService.port }}
