apiVersion: v1
kind: Service
metadata:
  name: {{ include "movie-service.fullname" . }}
  labels:
    {{- include "movie-service.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "movie-service.selectorLabels" . | nindent 6 }}
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
