apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.metadata.name }}
  labels:
    {{ .Values.metadata.name }}
spec:
  selector:
    {{ .Values.metadata.name }}
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8001
  type: ClusterIP
