apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-movie-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-movie-db
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-movie-db
    spec:
      containers:
      - name: movie-db
        image: {{ .Values.movieDB.image.repository }}:{{ .Values.movieDB.image.tag }}
        env:
        - name: POSTGRES_USER
          value: {{ .Values.movieDB.username }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.movieDB.password }}
        - name: POSTGRES_DB
          value: {{ .Values.movieDB.database }}
        ports:
        - containerPort: 5432
