apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-movie-db-service
spec:
  selector:
    app: {{ .Release.Name }}-movie-db
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
